name: release-binary
on:
    workflow_dispatch:
    push:
      tags:
        - '**'
env:
  PROJECT_NAME: MilitaryCardGame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: Build Binary
        run: bash build.sh

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          args: -vv --latest -c cocogitto --no-exec --github-repo ${{ github.repository }}
        env:
          config: cliff.toml
          OUTPUT: CHANGELOG.md

      - name : upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{env.PROJECT_NAME}}
          path: ./${{env.PROJECT_NAME}}_*

      - name: upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{env.PROJECT_NAME}}_*
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
          body: ${{ steps.git-cliff.outputs.changelog }}
          token: ${{ secrets.TOKEN }}
